### ISSUE TITLE
Missing data when importing `data/actb.gtf`

### ISSUE THREAD

**Issue by milanmlft** [carpentries-incubator/bioc-project#53]
Seems that something is going wrong [when importing](https://carpentries-incubator.github.io/bioc-project/07-genomic-ranges/index.html#importing-genomic-ranges-from-files) the `actb.gtf` file. The output doesn't show any ranges:

![Screen Shot 2022-10-21 at 12 54 26](https://user-images.githubusercontent.com/38256462/197180414-5f71c097-b960-4bc4-8577-f05e02a5b11d.png)

Relevant lines:
https://github.com/carpentries-incubator/bioc-project/blob/2300f76c95116829a2c3464e4a70d9e1b9784412/_episodes_rmd/07-genomic-ranges.Rmd#L494-L498

I can confirm that this problem also occurs when running the Rmd locally. I checked the raw data file and there doesn't seem to be a problem with that, so the issue arises during the import.

**Comment by kevinrue** [comment]
Oh right, I forgot about that but yeah, I noticed it myself a while back and keep forgetting to get to it.

Gold star for anyone who fixes it :)

**Comment by milanmlft** [comment]
Found it :)
